name: osrs

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - numpy
  - pandas
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - requests
  - pip
  - bs4
  - pyspark
  - cassandra-driver
